name: Deploy to FTP Server
on:
  push:
    branches: ["shivatest"]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy file
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: home562576484.1and1-data.host
          FTP_USERNAME: ${{ secrets.ftp_username }}
          FTP_PASSWORD: ${{ secrets.ftp_password }}
          local_path: './*'
          PORT: 22
          METHOD: sftp
          remote_path: '/site/IS436/lab5/shiva/'
          sftp_only: true
